<?php

namespace Database\Seeders;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Database\Seeder;

class AssignPermissionsToRoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return  void
     */
    public function run()
    {
         $userPermission = Permission::whereIn('name', [
                'create_query',
                'read_query',
                'update_query',
                'create_user',
                'read_user',
                'update_user',
                'delete_user',
                ])->get();

        /** @var  Role $userRole */
        $userRole = Role::where('name', 'User')->first();
        $userRole->givePermissionTo($userPermission);
 
        $adminPermission = Permission::whereIn('name', [
                'create_query',
                'read_query',
                'update_query',
                'delete_query',
                'create_user',
                'read_user',
                'update_user',
                'delete_user',
                'create_accomodation',
                'read_accomodation',
                'update_accomodation',
                'delete_accomodation',
                'create_accomodationfacitity',
                'read_accomodationfacitity',
                'update_accomodationfacitity',
                'delete_accomodationfacitity',
                'create_accreditation',
                'read_accreditation',
                'update_accreditation',
                'delete_accreditation',
                'create_accreditationhospital',
                'read_accreditationhospital',
                'update_accreditationhospital',
                'delete_accreditationhospital',
                'create_accomodationtype',
                'read_accomodationtype',
                'update_accomodationtype',
                'delete_accomodationtype',
                'create_designation',
                'read_designation',
                'update_designation',
                'delete_designation',
                'create_detoxificationcategory',
                'read_detoxificationcategory',
                'update_detoxificationcategory',
                'delete_detoxificationcategory',
                'create_detoxificationwellness',
                'read_detoxificationwellness',
                'update_detoxificationwellness',
                'delete_detoxificationwellness',
                'create_doctor',
                'read_doctor',
                'update_doctor',
                'delete_doctor',
                'create_doctorhospital',
                'read_doctorhospital',
                'update_doctorhospital',
                'delete_doctorhospital',
                'create_doctorpatienttestimonial',
                'read_doctorpatienttestimonial',
                'update_doctorpatienttestimonial',
                'delete_doctorpatienttestimonial',
                'create_doctorspecialization',
                'read_doctorspecialization',
                'update_doctorspecialization',
                'delete_doctorspecialization',
                'create_doctortag',
                'read_doctortag',
                'update_doctortag',
                'delete_doctortag',
                'create_doctortreatment',
                'read_doctortreatment',
                'update_doctortreatment',
                'delete_doctortreatment',
                'create_facility',
                'read_facility',
                'update_facility',
                'delete_facility',
                'create_hospital',
                'read_hospital',
                'update_hospital',
                'delete_hospital',
                'create_hospitaltags',
                'read_hospitaltags',
                'update_hospitaltags',
                'delete_hospitaltags',
                'create_hospitaltreatment',
                'read_hospitaltreatment',
                'update_hospitaltreatment',
                'delete_hospitaltreatment',
                'create_patientdetails',
                'read_patientdetails',
                'update_patientdetails',
                'delete_patientdetails',
                'create_patientfamilydetails',
                'read_patientfamilydetails',
                'update_patientfamilydetails',
                'delete_patientfamilydetails',
                'create_patienttestimony',
                'read_patienttestimony',
                'update_patienttestimony',
                'delete_patienttestimony',
                'create_patienttestimonytag',
                'read_patienttestimonytag',
                'update_patienttestimonytag',
                'delete_patienttestimonytag',
                'create_qualification',
                'read_qualification',
                'update_qualification',
                'delete_qualification',
                'create_role',
                'read_role',
                'update_role',
                'delete_role',
                'create_specialization',
                'read_specialization',
                'update_specialization',
                'delete_specialization',
                'create_specializationtreatment',
                'read_specializationtreatment',
                'update_specializationtreatment',
                'delete_specializationtreatment',
                'create_tags',
                'read_tags',
                'update_tags',
                'delete_tags',
                'create_test',
                'read_test',
                'update_test',
                'delete_test',
                'create_treatment',
                'read_treatment',
                'update_treatment',
                'delete_treatment',
                'create_wellnesscenter',
                'read_wellnesscenter',
                'update_wellnesscenter',
                'delete_wellnesscenter',
                'manage_roles'])->get();

        /** @var  Role $adminRole */
        $adminRole = Role::where('name', 'Admin')->first();
        $adminRole->givePermissionTo($adminPermission);
    }
}
